site_name: yapp-pipelines
repo_url: https://github.com/cavenditti/yapp
repo_name: cavenditti/yapp

nav:
    - Introduction: index.md
    - Configuration: configuration.md
    - Roadmap: roadmap.md
    - Reference: reference.md

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    #- navigation.tabs
    #- navigation.sections
    - toc.integrate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red
      accent: teal
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: teal
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  icon:
    logo: material/pipe
    repo: fontawesome/brands/github

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/cavenditti/yapp
      name: cavenditti/yapp
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/yapp-pipelines/
      name: yapp-pipelines

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
- search
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        rendering:
          show_source: false
          show_root_heading: true
          heading_level: 2

